language: android
env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=24
   - ANDROID_BUILD_TOOLS=28.0.3
   - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - sys-img-$ANDROID_ABI-android-$EMULATOR_API_LEVEL
before_script:
  - echo no | android create avd --force --name test --target android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n$ANDROID_KEY_A" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n$ANDROID_KEY_B" > "$ANDROID_HOME/licenses/android-sdk-license"
script:
  - ./gradlew build connectedCheck -x test -x lint -x connectedDebugAndroidTest --stacktrace
